/**
 * Generated by scripts/generate-classifications.mjs from the
 * "beverage_classifications" row of src/canonical/reference-data.json.
 * Do not edit by hand; run `pnpm generate:classifications` (or
 * `pnpm sync-canonical`, which calls it automatically after every sync).
 */
import type { BeverageClassification } from "./types.js";

export const CANONICAL_CLASSIFICATIONS: BeverageClassification = {
  "categories": [
    {
      "id": "wine",
      "name": "Still Wine",
      "hsHeading": "2204",
      "subtypes": [
        {
          "id": "red",
          "name": "Red Wine",
          "oivType": "1"
        },
        {
          "id": "white",
          "name": "White Wine",
          "oivType": "2"
        },
        {
          "id": "rose",
          "name": "Rosé Wine",
          "oivType": "3"
        },
        {
          "id": "orange",
          "name": "Orange Wine"
        },
        {
          "id": "natural",
          "name": "Natural Wine"
        },
        {
          "id": "dessert",
          "name": "Dessert Wine",
          "oivType": "6"
        }
      ]
    },
    {
      "id": "sparkling_wine",
      "name": "Sparkling Wine",
      "hsHeading": "2204",
      "subtypes": [
        {
          "id": "white",
          "name": "White Sparkling"
        },
        {
          "id": "rose",
          "name": "Rosé Sparkling"
        },
        {
          "id": "red",
          "name": "Red Sparkling"
        }
      ]
    },
    {
      "id": "fortified_wine",
      "name": "Fortified Wine",
      "hsHeading": "2204",
      "subtypes": [
        {
          "id": "port",
          "name": "Port",
          "oivType": "5"
        },
        {
          "id": "sherry",
          "name": "Sherry & Montilla",
          "oivType": "5"
        },
        {
          "id": "madeira",
          "name": "Madeira",
          "oivType": "5"
        }
      ]
    },
    {
      "id": "vermouth",
      "name": "Vermouth & Aromatized Wine",
      "hsHeading": "2205",
      "subtypes": [
        {
          "id": "sweet_vermouth",
          "name": "Sweet Vermouth"
        },
        {
          "id": "dry_vermouth",
          "name": "Dry Vermouth"
        },
        {
          "id": "other_aromatized",
          "name": "Other Aromatized"
        }
      ]
    },
    {
      "id": "beer",
      "name": "Beer",
      "hsHeading": "2203",
      "subtypes": [
        {
          "id": "lager",
          "name": "Lager"
        },
        {
          "id": "ale",
          "name": "Ale"
        },
        {
          "id": "ipa",
          "name": "IPA"
        },
        {
          "id": "stout",
          "name": "Stout"
        },
        {
          "id": "wheat_beer",
          "name": "Wheat Beer"
        },
        {
          "id": "pilsner",
          "name": "Pilsner"
        },
        {
          "id": "porter",
          "name": "Porter"
        },
        {
          "id": "sour",
          "name": "Sour"
        }
      ]
    },
    {
      "id": "spirits",
      "name": "Spirits",
      "hsHeading": "2208",
      "subtypes": [
        {
          "id": "whisky",
          "name": "Whisky"
        },
        {
          "id": "vodka",
          "name": "Vodka"
        },
        {
          "id": "gin",
          "name": "Gin"
        },
        {
          "id": "rum",
          "name": "Rum"
        },
        {
          "id": "tequila",
          "name": "Tequila"
        },
        {
          "id": "brandy",
          "name": "Brandy"
        },
        {
          "id": "liqueur",
          "name": "Liqueur"
        },
        {
          "id": "grappa",
          "name": "Grappa"
        }
      ]
    },
    {
      "id": "cider_mixed_drinks",
      "name": "Cider, Perry, Mead & Mixed",
      "hsHeading": "2206",
      "subtypes": [
        {
          "id": "dry_cider",
          "name": "Dry Cider"
        },
        {
          "id": "sweet_cider",
          "name": "Sweet Cider"
        },
        {
          "id": "fruit_cider",
          "name": "Fruit Cider"
        },
        {
          "id": "perry",
          "name": "Perry"
        },
        {
          "id": "mead",
          "name": "Mead"
        },
        {
          "id": "sake",
          "name": "Sake"
        }
      ]
    },
    {
      "id": "flavored_wine",
      "name": "Flavored & Fruit Wine",
      "hsHeading": "2206",
      "subtypes": [
        {
          "id": "fruit_wine",
          "name": "Fruit Wine"
        },
        {
          "id": "flavored_wine",
          "name": "Flavored Wine"
        }
      ]
    },
    {
      "id": "non_alcoholic",
      "name": "Non-Alcoholic",
      "hsHeading": "2202",
      "subtypes": [
        {
          "id": "na_beer",
          "name": "Non-Alcoholic Beer"
        },
        {
          "id": "na_wine",
          "name": "Non-Alcoholic Wine"
        },
        {
          "id": "na_spirits",
          "name": "Non-Alcoholic Spirits"
        }
      ]
    },
    {
      "id": "other",
      "name": "Other",
      "hsHeading": "",
      "subtypes": [
        {
          "id": "mulled_wine",
          "name": "Mulled Wine"
        },
        {
          "id": "other",
          "name": "Other"
        }
      ]
    }
  ]
};
